apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-deployment
  namespace: chat-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: chatapp-backend
          image: shubham34343s/chatapp-backend:latest

          ports:
            - containerPort: 5001

          env:
            - name: PORT
              value: "5001"

            - name: NODE_ENV
              value: "production"

            - name: MONGODB_URI
              value: "mongodb://root:root@mongodb-service:27017/chatapp?authSource=admin"

          envFrom:
            - secretRef:
                name: chatapp-secrets

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi

          readinessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 15
            periodSeconds: 20
